/**
 * Created by Bartlomiej Rutkowski on 19.09.16.
 */
const CONSTANTS = {
  REGISTER_USER: 'REGISTER_USER',
  AUTHENTICATE_USER: 'AUTHENTICATE_USER',
  LOGIN: 'LOGIN',
  AUTHENTICATE_WITH_TOKEN: 'AUTHENTICATE_WITH_TOKEN',
  LOGOUT: 'LOGOUT'
};

export default CONSTANTS;
